# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Lukas Wolfsteiner
description: senior software engineer with a proven track record to develop and deliver high-quality software solutions
email: lukas@wolfsteiner.media

# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lukas.wolfsteiner.media" # the base hostname & protocol for your site, e.g. http://example.com

timezone: Europe/Berlin

# Build settings
markdown: kramdown

# Force UTF-8 encoding
encoding: UTF-8

# Custom plugins
plugins_dir: ./_plugins

plugins:
  - jekyll-sitemap
  - jekyll-favicon
  - jekyll-seo-tag
  - jekyll-last-modified-at
  - jekyll/mastodon_webfinger
  - jekyll-target-blank
  - jekyll-redirect-from

# Config for jekyll/mastodon_webfinger
mastodon:
  username: dotwee
  instance: sueden.social

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .DS_Store
  - compose.yml
  - LICENSE
  - CNAME

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Config for jekyll-last-modified-at
last-modified-at:
  date-format: '%Y-%m-%d'

# Config for jekyll-favicon
favicon:
  source: favicon.svg

# Config for jekyll-seo-tag
logo: /favicon.png
author: lukaswolfsteiner

twitter:
  username: dnkncht
  card: summary

social:
  name: Lukas Wolfsteiner
  links:
    - https://twitter.com/dnkncht
    - https://www.xing.com/profile/Lukas_Wolfsteiner2
    - https://www.linkedin.com/in/lukas-wolfsteiner
    - https://instagram.com/dnkncht
    - https://github.com/dotWee
    - https://keybase.io/dotwee

# Config for jekyll-target-blank
target-blank:
  noopener: false
  noreferrer: false
  rel: me
  rel_exclude: 
    - kdv-fh-bayern.de
    - weigertkunde.de

# Config for jekyll-redirect-from
redirect_from:
  json: false
