# usage:
#   docker compose up -d

services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --force_polling --livereload
    volumes:
      - $PWD:/srv/jekyll
    ports:
      - 4000:4000