name: Jekyll Build & Deploy

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use ruby/setup-ruby to shorten build times
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7 # Not needed with a .ruby-version file
          bundler-cache: true

      - name: Install dependencies & build site using jekyll
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true

      - name: Safe built site as artifact
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: ./_site/
          if-no-files-found: error

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download static webpage files
        uses: actions/download-artifact@v2
        with:
          name: site

      - name: Display structure of downloaded files
        run: ls -R

      - name: Deploy site to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          allow_empty_commit: true
