name: Jekyll Build & Deploy

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate static website
    steps:
      - uses: actions/checkout@v3

      - name: Use ruby/setup-ruby to shorten build times
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 2.7
          
      - name: Install dependencies & build site using jekyll
        uses: limjh16/jekyll-action-ts@v2

      - name: Persist built site as artifact
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: ./_site/
          if-no-files-found: error

  deploy:
    needs: generate
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    name: Deploy generated site to GitHub pages
    steps:
      - name: Download static webpage files
        uses: actions/download-artifact@v2
        with:
          name: site

      - name: Deploy site to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          allow_empty_commit: true
          
