name: Jekyll Build & Deploy

on:
  # Run this workflow on push events
  push:
    branches:
      - $default-branch # Default branch is the branch set in the repository settings
      - "feature/*" # Run on feature branches
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate static website
    steps:
      - uses: actions/checkout@v4

      - name: Add ImageMagick for image processing
        run: sudo apt-get install imagemagick -y

      - name: Use ruby/setup-ruby to shorten build times
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 4 # Increment this number if you need to re-download cached gems

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v3

      - name: Push resume.json to Gist
        uses: dotWee/push-gist-action@4c72e19c032cbea15ed6f1a52bacef59e21292eb
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: 46a00ab755cd7904a344463556017670
          file_path: ./_site/assets/resume.json
          gist_file_name: resume.json

  deploy:
    name: Deploy generated site to GitHub pages
    needs: generate
    
    # Only deploy on pushes to the default branch
    if: github.ref == "refs/heads/${{ github.event.repository.default_branch }}"
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
